[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "CE_sandbox"
version = "0.1.0"

[tool.setuptools]
package-dir = {"" = "src"}
packages = ["ns_solvers"]

[project.scripts]
ns_driver = "ns_solvers.driver:main"